// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBankData() {
  return window['go']['main']['App']['GetBankData']();
}

export function GetCashData() {
  return window['go']['main']['App']['GetCashData']();
}
